model_params:
  input_dim: 2
  latent_dim: 2
  hidden_dim: 32

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  accelerator: 'gpu'
  max_epochs: 100
  
